[functions.generate-prompts]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.redo-image]
verify_jwt = false

[functions.generate-final-video]
verify_jwt = false

[functions.generate-full-video]
verify_jwt = false
